branches:
  only:
    - master
    - develop
    - /^(feature|release)\/.*$/
os: linux
language: node_js
node_js: '10'
cache: npm
before_install:
  - npm i -g npm@latest
  - export PATH="$HOME/node_modules/.bin:$PATH"
script:
  - npm run lint
  - npm run test
  - npm run package:build
  - npm run handbook:build
  - npm run handbook-insight-viewer-sample:build
  - npm run handbook-new-window-sample:build
  - npm run ui-guideline:build
deploy:
  # npm publish
  - provider: script
    script: npm run package:publish:ci
    skip_cleanup: true
    on:
      branch: master
  # handbook
  - provider: pages
    skip_cleanup: true
    token: $GITHUB_TOKEN
    keep_history: true
    local_dir: ./dist/handbook/browser
    target_branch: dist/handbook/$TRAVIS_BRANCH
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^(master|develop|feature|release)
  # handbook samples
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: ./dist/handbook-insight-viewer-sample/browser
    target_branch: dist/handbook-insight-viewer-sample
    on:
      all_branches: true
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: ./dist/handbook-new-window-sample/browser
    target_branch: dist/handbook-new-window-sample
    on:
      all_branches: true
  # https://lunit-io.github.io/ui-guideline
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: ./dist/ui-guideline/browser
    repo: lunit-io/ui-guideline
    on:
      all_branches: true
notifications:
  email:
    on_success: never
    on_failure: always