name: Deploy insight-viewer on develop

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - .github/workflows/insight-viewer-feature.yml
      - packages/insight-viewer/**
      - apps/insight-viewer-docs/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Get Yarn cache directory
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Yarn build
        id: yarn-build
        run: |
          yarn install --prefer-offline
          yarn doc:insight-viewer

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id:     ${{ secrets.CDN_FOR_PREVIEW_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.CDN_FOR_PREVIEW_SECRET_KEY }}
          aws-region:            us-east-1

      - name: Deploy
        env:
          HOST: insight-viewer--pr-${{ github.event.number }}.f.lunit.io
        run: |
          aws s3 sync \
            ./dist s3://lunit-cdn-for-preview-virginia/${HOST} \
            --delete

      - name: Preview link
        uses: NejcZdovc/comment-pr@v1.1.1
        with:
          file: "comment.md"
          identifier: "GITHUB_COMMIT_FILE"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PR_ID: ${{github.event.number}}
